### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by bryanjhv** [bryanjhv/ruby2go#1]
The Firefox OS Marketplace closed early in September, and so the `README` needs to be updated to not reference it anymore.

**Comment by crazcalm** [comment]
Do you mind If I take this issue?

**Comment by bryanjhv** [comment]
@crazcalm Yeah, you're free to do so. But, please, do not remove the "Usage" section, it makes people see this is not an app.

**Comment by crazcalm** [comment]
@bryanjhv Currently, the only thing in the "Usage" section is the reference to the marketplace. Do you want me to leave that section empty or do you have some info that I can add to that section?

**Comment by bryanjhv** [comment]
I updated my previous comment here. Also, if you can write a phrase to let users expect something (maybe a *soon this app will become yours* might do the job).

**Comment by crazcalm** [comment]
@bryanjhv is this good? https://github.com/bryanjhv/ruby2go/pull/6

**Comment by bryanjhv** [comment]
@crazcalm merged right now, thanks for contributing. Have a happy #Hacktoberfesting :smile_cat:

**Comment by crazcalm** [comment]
@bryanjhv Thank you for letting me help!
