### ISSUE TITLE
Smartphones Go

### ISSUE THREAD

**Issue by Marc14Sala** [bryanjhv/ruby2go#8]
Seria un juego de Realidad Aumentada para jugar en la calle del Mundo Real en que el jugador tiene su propia empresa de smartphones i Mientras va recogiendo objetos por la calle de mundo real con los objetos se va construiendo los smartphones. Es decir cada objeto es una pieza el smartphone por ejemplo una camara. Quando el jugador a construido un smartphone el juego vàlua: sus carecteristicas el precio i las ventas/copias i entonces entoneces se consigen puntos de exp para el jugador los puntos de exp significa el dinero ingresado, por ejemplo un objeto recojido son 50xp es decir 50€ ingresados però necesitas 200000€ para llegar a nivel 2, a cada nivel subido salen mas objetos diferentes o un objeto mejorado, por ejemplo si supongamos que estamos al nivel 7 i con 800000€ pasos al nivel 8 nos sale una memòria interna mas potente i varios objetos que no teniamos antes. 

Mas o menos ese es mi proyecto.

Muchas gracias:
Marc Sala Ferrer

**Comment by bryanjhv** [comment]
I'm not sure I understand your question/problem/anything.
Is it a bug? A feature request? A comment? Something related?

Feel free to comment so I might reopen this if this something useful.
Also, please try to write in English, the language this repository is written in.
PS: I'm fluent in Spanish but GitHub suggests to write in their language.
